hl.on("hyprland.start", function () 
   hl.exec_cmd("nm-applet")
   hl.exec_cmd("ashell &")
   hl.exec_cmd("awww-daemon &")
   hl.exec_cmd("snappy-switcher --daemon &")
   hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" &')
   hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark" &')
   hl.exec_cmd("thunar --daemon &")
   hl.exec_cmd("kitty")
   hl.exec_cmd("kitty weathr")
   hl.exec_cmd("kitty htop")
   hl.exec_cmd("awww img /tmp/wallpaper")
 end)
